@echo off
TASKKILL /F /IM HDPSrv.exe
TASKKILL /F /IM hkcmd.exe
TASKKILL /F /IM NBSUTool.exe
TASKKILL /F /IM prldsrv.exe
TASKKILL /F /IM SearchIndexer.exe
TASKKILL /F /IM taskeng.exe
TASKKILL /F /IM HDPSrv.exe
TASKKILL /F /IM "cacaoweb.exe"
TASKKILL /F /IM "sppsvc.exe"
TASKKILL /F /IM "MsMpEng.exe"
TASKKILL /F /IM "soffice.bin"
TASKKILL /F /IM "googletalkplugin.exe"
TASKKILL /F /IM "msseces.exe"
TASKKILL /F /IM "AODAssist.exe"
TASKKILL /F /IM "PnkBstrA.exe"
TASKKILL /F /IM "jusched.exe"
TASKKILL /F /IM "raysat_3dsmax2011_64server.exe"
TASKKILL /F /IM "raysat_3dsmax2011_32server.exe"
TASKKILL /F /IM "WLIDSVCM.exe"
TASKKILL /F /IM "AppleMobileDeviceService.exe"
TASKKILL /F /IM "TrustedInstaller.exe"
TASKKILL /F /IM "atieclxx.exe"
TASKKILL /F /IM "MOM.exe"
TASKKILL /F /IM "iPodService.exe"
TASKKILL /F /IM "iTunesHelper.exe"
TASKKILL /F /IM "armsvc.exe"
TASKKILL /F /IM "atiesrxx.exe"
TASKKILL /F /IM "Connect.Service.ContentService.exe"
TASKKILL /F /IM "CCC.exe"
TASKKILL /F /IM "BambooCore.exe"
TASKKILL /F /IM "CLIStart.exe"
TASKKILL /F /IM "Connect.Service.ContentService.exe"
TASKKILL /F /IM "DTLite.exe	"
TASKKILL /F /IM "TabTip.exe"
TASKKILL /F /IM "TabTip32.exe"
TASKKILL /F /IM "wisptis.exe"
TASKKILL /F /IM "WLIDSVC.exe"
TASKKILL /F /IM "Pen_TabletUser.exe"
TASKKILL /F /IM "B4-Service.exe"
TASKKILL /F /IM "B4-Capture.exe"
TASKKILL /F /IM "Pen_TouchUser.exe"
TASKKILL /F /IM "TabTip32.exe"





NET STOP "Themes"
NET STOP "SPOOLER"
NET STOP "Schedule"
NET STOP "SysMain"
NET STOP "TrkWks"
NET STOP "PlugPlay"
NET STOP "MpsSvc"
NET STOP "lmhosts"
NET STOP "iphlpsvc"
NET STOP "CryptSvc"
NET STOP "BITS"
NET STOP "WSearch"
NET STOP "WinDefend"
NET STOP "WinHttpAutoProxySvc"
NET STOP "FontCache"
NET STOP "wuauserv"
NET STOP "SSDPSRV"
NET STOP "StiSvc"
NET STOP "Schedule"
NET STOP "AeLookupSvc"
NET STOP "BITS"
NET STOP "SSDPSRV"
NET STOP "Wsearch"
NET STOP "wuauserv"
NET STOP "SENS"
NET STOP "LogMeIn"
NET STOP "LMIGuardianSvc"
NET STOP "LMIMaint"
NET STOP "CryptSvc"
NET STOP "wuauserv"
NET STOP "Winmgmt"
NET START "Themes"